"""Added Student model

Revision ID: 6021b50636bb
Revises: 6109a7bfe3d0
Create Date: 2024-01-12 18:15:21.087581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6021b50636bb'
down_revision = '6109a7bfe3d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
